/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProfileOptimizationService } from "../profileOptimization.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProfileOptimizationCreateInput } from "./ProfileOptimizationCreateInput";
import { ProfileOptimization } from "./ProfileOptimization";
import { ProfileOptimizationFindManyArgs } from "./ProfileOptimizationFindManyArgs";
import { ProfileOptimizationWhereUniqueInput } from "./ProfileOptimizationWhereUniqueInput";
import { ProfileOptimizationUpdateInput } from "./ProfileOptimizationUpdateInput";
import { UpdateProfileOptimizationArgs } from "./UpdateProfileOptimizationArgs";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProfileOptimizationControllerBase {
  constructor(
    protected readonly service: ProfileOptimizationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProfileOptimization })
  @nestAccessControl.UseRoles({
    resource: "ProfileOptimization",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createProfileOptimization(
    @common.Body() data: ProfileOptimizationCreateInput
  ): Promise<ProfileOptimization> {
    return await this.service.createProfileOptimization({
      data: {
        ...data,

        appUser: data.appUser
          ? {
              connect: data.appUser,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        appUser: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        optimizedProfileData: true,
        profileData: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ProfileOptimization] })
  @ApiNestedQuery(ProfileOptimizationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProfileOptimization",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async profileOptimizations(
    @common.Req() request: Request
  ): Promise<ProfileOptimization[]> {
    const args = plainToClass(ProfileOptimizationFindManyArgs, request.query);
    return this.service.profileOptimizations({
      ...args,
      select: {
        appUser: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        optimizedProfileData: true,
        profileData: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProfileOptimization })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProfileOptimization",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async profileOptimization(
    @common.Param() params: ProfileOptimizationWhereUniqueInput
  ): Promise<ProfileOptimization | null> {
    const result = await this.service.profileOptimization({
      where: params,
      select: {
        appUser: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        optimizedProfileData: true,
        profileData: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProfileOptimization })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProfileOptimization",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateProfileOptimization(
    @common.Param() params: ProfileOptimizationWhereUniqueInput,
    @common.Body() data: ProfileOptimizationUpdateInput
  ): Promise<ProfileOptimization | null> {
    try {
      return await this.service.updateProfileOptimization({
        where: params,
        data: {
          ...data,

          appUser: data.appUser
            ? {
                connect: data.appUser,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          appUser: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          optimizedProfileData: true,
          profileData: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProfileOptimization })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProfileOptimization",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProfileOptimization(
    @common.Param() params: ProfileOptimizationWhereUniqueInput
  ): Promise<ProfileOptimization | null> {
    try {
      return await this.service.deleteProfileOptimization({
        where: params,
        select: {
          appUser: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          optimizedProfileData: true,
          profileData: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Post("/profileOptimization")
  @swagger.ApiOkResponse({
    type: ProfileOptimization,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async CreateProfileOptimization(
    @common.Body()
    body: UpdateProfileOptimizationArgs
  ): Promise<ProfileOptimization> {
    return this.service.CreateProfileOptimization(body);
  }

  @common.Delete("/profileOptimization/:id")
  @swagger.ApiOkResponse({
    type: Boolean,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async DeleteProfileOptimization(
    @common.Body()
    body: UpdateProfileOptimizationArgs
  ): Promise<boolean> {
    return this.service.DeleteProfileOptimization(body);
  }

  @common.Get("/profileOptimization/:id")
  @swagger.ApiOkResponse({
    type: ProfileOptimization,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async GetProfileOptimization(
    @common.Body()
    body: UpdateProfileOptimizationArgs
  ): Promise<ProfileOptimization> {
    return this.service.GetProfileOptimization(body);
  }

  @common.Put("/profileOptimization/:id")
  @swagger.ApiOkResponse({
    type: ProfileOptimization,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async UpdateProfileOptimization(
    @common.Body()
    body: UpdateProfileOptimizationArgs
  ): Promise<ProfileOptimization> {
    return this.service.UpdateProfileOptimization(body);
  }
}
