/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { EnumAppUserLoginProvider } from "./EnumAppUserLoginProvider";
import { ProfileOptimizationCreateNestedManyWithoutAppUsersInput } from "./ProfileOptimizationCreateNestedManyWithoutAppUsersInput";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SessionCreateNestedManyWithoutAppUsersInput } from "./SessionCreateNestedManyWithoutAppUsersInput";

@InputType()
class AppUserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  authenticationId?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumAppUserLoginProvider,
  })
  @IsEnum(EnumAppUserLoginProvider)
  @IsOptional()
  @Field(() => EnumAppUserLoginProvider, {
    nullable: true,
  })
  loginProvider?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProfileOptimizationCreateNestedManyWithoutAppUsersInput,
  })
  @ValidateNested()
  @Type(() => ProfileOptimizationCreateNestedManyWithoutAppUsersInput)
  @IsOptional()
  @Field(() => ProfileOptimizationCreateNestedManyWithoutAppUsersInput, {
    nullable: true,
  })
  profileOptimizations?: ProfileOptimizationCreateNestedManyWithoutAppUsersInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  profilePicture?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => SessionCreateNestedManyWithoutAppUsersInput,
  })
  @ValidateNested()
  @Type(() => SessionCreateNestedManyWithoutAppUsersInput)
  @IsOptional()
  @Field(() => SessionCreateNestedManyWithoutAppUsersInput, {
    nullable: true,
  })
  sessions?: SessionCreateNestedManyWithoutAppUsersInput;
}

export { AppUserCreateInput as AppUserCreateInput };
